fix and improve aafm exe

diff --git a/aafm b/aafm
--- a/aafm
+++ b/aafm
@@ -7,9 +7,9 @@ site_path=""
 #version lower than 2.5.0
 
 which python > /dev/null 2>&1
-if [ "$?" == "0" ]; then
+if [ $? -eq 0 ]; then
 	version=$(python -c 'import sys; print(sys.version[:1])')
-	if [ "$version" = "2" ]; then
+	if [ $version -eq 2 ]; then
 		executable=python
 	fi
 fi
@@ -48,6 +48,23 @@ fi
 #Assume we have actually installed aafm to the site-packages dir....
 site_path="$($executable -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")"
 
+# check if site_path exists, and check if its in other common locations
 #Launch Aafm from site-packages path and pass any arguments given
-$executable "${site_path}/aafm/aafm-gui.py" "$@"
-
+if [ -e "${site_path}/aafm/aafm-gui.py" ]; then
+	echo "Running: $executable ${site_path}/aafm/aafm-gui.py $@"
+	$executable "${site_path}/aafm/aafm-gui.py" "$@"
+elif [ -e `echo "${site_path}/aafm/aafm-gui.py" | sed -e 's#/lib/#/local/lib/#'` ]; then
+	echo "Running: $executable ${site_path}/aafm/aafm-gui.py $@" | sed -e 's#/lib/#/local/lib/#'
+	$executable `echo "${site_path}/aafm/aafm-gui.py" | sed -e 's#/lib/#/local/lib/#'` "$@"
+elif [ -e "~/Applications/aafm/src/aafm-gui.py" ]; then
+	echo "Running: $executable ~/Applications/aafm/src/aafm-gui.py $@"
+	$executable "~/Applications/aafm/src/aafm-gui.py" "$@"
+elif [ -e "src/aafm-gui.py" ]; then
+	echo "Running: $executable src/aafm-gui.py $@"
+	$executable "src/aafm-gui.py" "$@"
+else
+	echo "Error: aafm-gui.py not found"
+	exit 1
+fi
+		
+exit 0
